### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by Mixarar** [Siris01/clyde-tui#1]
You are literally the only person that i found who made some sort of Clyde interface interaction outside of Discord. I know it has been over 4 month since last commit, but would it be possible to make some sort of a reverse proxy for openAI libraries? So that you can use OpenAI API library for essentially limitless free GTP 3.5

**Comment by siriscmv** [comment]
OpenAI libraries require an OpenAI API token which is not free. If you mean creating a proxy for ChatGPT there are some out there  but they break often

**Comment by Mixarar** [comment]
Yeah no you can also change the OpenAI endpoint url to something else, and then just use openai libraries to interact with the api, so it would be cool to have an API for discord clyde. Oh and most proxies out there are Paid, and they yeah dont work often and overall are poorly made.

**Comment by siriscmv** [comment]
I dont understand what you are asking for, this repo simply sends messages and displays back clyde's responses. There is no "API" for discord clyde, other than sending a normal msg in a clyde-enabled channel using discord's message endpoint

**Comment by Mixarar** [comment]
Yeah i know thats what the point of my message was. Making an API that would allow to send and get messages from clyde.

**Comment by siriscmv** [comment]
Then yes, it is possible using the Discord API, use this [endpoint](https://discord.com/developers/docs/resources/channel#create-message) to send messages, and the connect to the gateway/poll for channel's messages to get the response. 

I will not be implementing this here since it is outside the scope of this project. 
Obviously this will not be compatible with OpenAI libraries without making heavy modifications/rewriting it.
